### ISSUE TITLE
컨테이너(IDE) 공유 링크 초대시 익명일 경우 

### ISSUE THREAD

**Issue by SSUK-H** [ExceptAnyone/SSAP-IDE-FrontEnd#12]
## 작업 사항

> 컨테이너(IDE) 공유 링크를 통해 사용자가 접속했을 때 로그인 상태일 때는 사용자 정보를 넘겨 받을 수 있는데 로그아웃 상태일 때 로그인을 하도록 로그인 창을 띄울건지 익명일 경우에도 접속이 가능하게 할 건지 정해야할 것 같습니다! 

## To-do
- [ ] 입력해주세요.

## 기타사항

> #4 추가 필요

**Comment by cipp00h** [comment]
Web IDE 프로젝트 정보 조회 API 호출 후, Respone 데이터에 로그인한 사용자의 ID와 name 정보를 같이 담아 반환하도록 해야 한다. 프론트에서는 ID와 name 정보를 상태관리 해야 하며, 이 정보는 채팅 기능에서 활용된다.

**Comment by SSUK-H** [comment]
그럼 공유링크 초대시 익명은 제외하고 로그인을 하도록 진행하겠습니다.
